name: Notify PR Review Request

on:
  pull_request:
    branches: [ dev-be ]
    paths:
      - 'backend/**'

jobs:
  BE_SLACK:
    runs-on: ubuntu-latest
    steps:
      - name: Make Review Request Message
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = `${{ github.event.pull_request.number }} ${github.event.pull_request.title}`;
            const url = `${{ github.event.pull_request.html_url }}`;
            const reviewers = `${{ github.event.pull_request.requested_reviewers.map(el => el.name).join(', ') }}`;

            const blocks = [
              { type: 'header', text: { type: 'plain_text', text: '👀 PR 리뷰 요청' } },
              { type: 'divider' },
              {
                type: 'section',
                text: {
                  type: 'mrkdwn',
                  text: `${title}\n${url}\nReviewers: ${reviewers}`
                }
              }
            ];

            return { blocks: blocks };

      - name: Send Slack message
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: ${{ toJson(steps.Make Review Request Message.outputs.result.blocks) }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
