name: Notify PR Review Request

on:
  pull_request:
    branches:
      - dev-be
    types:
      - review_requested
    paths:
      - 'backend/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Make Review Request Message
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const messageBlocks = [
              { "type": "header", "text": { "type": "plain_text", "text": "👀 PR 리뷰 요청" } },
              { "type": "divider" },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": `
                    PR Number: ${{ github.event.pull_request.number }}
                    Title: ${{ github.event.pull_request.title }}
                    URL: ${{ github.event.pull_request.html_url }}
                    Reviewers: ${{ github.event.pull_request.requested_reviewers.map(el => el.login).join(', ') }}
                  `
                }
              }
            ];
            console.log(JSON.stringify({ blocks: messageBlocks }));

      - name: Send Slack message
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: ${{ steps.pulls.outputs.result }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
