name: "Chromatic"

on: push

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          cd frontend
          yarn install --frozen-lockfile
      - name: Run Chromatic
        id: publish_chromatic
        run: |
          cd frontend
          npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: "🚀 **storybook**: ${{ steps.publish_chromatic.outputs.storybookUrl }}"
