name: 'Chromatic Deployment'

on:
  pull_request:
    branches: [dev-fe]
    paths:
      - '**/*.stories.tsx'
  push:
    branches: [dev-fe]
    paths:
      - '**/*.stories.tsx'

  workflow_dispatch:

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set node linker to node-modules
        run: |
          cd frontend
          yarn config set nodeLinker "node-modules"

      - name: Install dependencies
        run: |
          cd frontend
          yarn install --immutable --check-cache

      - name: Build Storybook
        run: |
          cd frontend
          yarn run build-storybook

      - name: List files in frontend
        run: |
          cd frontend
          ls -la

      - name: Publish to Chromatic
        id: publish_chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build-storybook
          onlyChanged: true
          storybookBaseDir: frontend

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v1
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: '🚀 **storybook**: ${{ steps.publish_chromatic.outputs.storybookUrl }}'
