# Workflow name
name: "Chromatic Deployment"

on:
  pull_request:
    branches:
      - dev-fe
      - feat/**
    paths:
      - frontend/**
      - .github/**
  push:
    branches:
      - dev-fe
      - feat/**
    paths:
      - frontend/**
      - .github/**

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    # Job steps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn
      - name: Run Chromatic
        uses: chromaui/action@v2
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
