name: 'Chromatic Deployment'

on:
  pull_request:
    branches:
      - dev-fe
    paths:
      - frontend/**
      - .github/**

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List files at root
        run: ls -la

      - name: List files in frontend
        run: ls -la frontend

      - name: Set node linker to node-modules
        run: yarn config set nodeLinker "node-modules"
        working-directory: frontend

      - name: Install dependencies
        run: yarn install --immutable --check-cache
        working-directory: frontend

      - name: Build Storybook
        run: yarn run build-storybook
        working-directory: frontend

      - name: Publish to Chromatic
        id: publish_chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build-storybook
          onlyChanged: true
          storybookBaseDir: frontend

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v1
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: '🚀 **storybook**: ${{ steps.publish_chromatic.outputs.storybookUrl }}'
